### ISSUE TITLE
コメント

### ISSUE THREAD

**Issue by c0b21093** [c0b2101536/ProjExD#9]
https://github.com/c0b2101536/ProjExD/blob/ca2f061462d77258a356ef6f99f0a6e26f4e0713/ex03/maze.py#L3

ゴールした時に動きを止める機能ですが私はゴールの座標に工科トンがついたときリアルタイム関数を中断するようmain_proc関数でafter_cancelを使いました。

**Comment by c0b2101536** [comment]
after_cancelは思い浮かばなかったです。
